# below is the zsh prompt configuration
# options docs: https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html
# color chart: https://upload.wikimedia.org/wikipedia/commons/1/15/Xterm_256color_chart.svg
autoload -U colors && colors
export PROMPT="$fg[black]%(?.%{$bg[green]%}%n.%{$bg[red]%} %? %n)%K{016}%F{123}@%F{025}%m$reset_color %F{135}%1~ %F{226}$%F{015}$reset_color"


eval "$(direnv hook zsh)"

# when using zsh in vi mode the history search binding is changed to be different
# from ^r. Change it back for familiarity and consistency
bindkey '^r' history-incremental-search-backward

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
